[package]
name = "carapace"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["net", "rt-multi-thread", "macros", "sync"] }
tracing = "0.1"
tracing-subscriber = "0.3"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "stun_benchmark"
harness = false
